<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ModelCar extends Seeder
{
  /**
   * Run the database seeds.
   */
  public function run(): void
  {
    DB::table('model_cars')->insert([
        # seeder mercedes model
        ['brand_id' => 1, 'model_name' => 'GLC'],
        ['brand_id' => 1, 'model_name' => 'C class'],
        ['brand_id' => 1, 'model_name' => 'E class'],
        ['brand_id' => 1, 'model_name' => 'S class'],
        ['brand_id' => 1, 'model_name' => 'Maybach'],
        ['brand_id' => 1, 'model_name' => 'G class'],
        ['brand_id' => 1, 'model_name' => 'GLS'],
        ['brand_id' => 1, 'model_name' => 'GLE Class'],
        ['brand_id' => 1, 'model_name' => 'GLB'],
        ['brand_id' => 1, 'model_name' => '190'],
        ['brand_id' => 1, 'model_name' => 'AMG GT'],
        ['brand_id' => 1, 'model_name' => 'Atego'],
        ['brand_id' => 1, 'model_name' => 'A class'],
        ['brand_id' => 1, 'model_name' => 'B class'],
        ['brand_id' => 1, 'model_name' => 'CLA class'],
        ['brand_id' => 1, 'model_name' => 'CLK class'],
        ['brand_id' => 1, 'model_name' => 'CLS class'],
        ['brand_id' => 1, 'model_name' => 'CL class'],
        ['brand_id' => 1, 'model_name' => 'EQB'],
        ['brand_id' => 1, 'model_name' => 'EQE'],
        ['brand_id' => 1, 'model_name' => 'EQS'],
        ['brand_id' => 1, 'model_name' => 'GL'],
        ['brand_id' => 1, 'model_name' => 'GLA class'],
        ['brand_id' => 1, 'model_name' => 'GLK Class'],
        ['brand_id' => 1, 'model_name' => 'MB'],
        ['brand_id' => 1, 'model_name' => 'ML Class'],
        ['brand_id' => 1, 'model_name' => 'M class'],
        ['brand_id' => 1, 'model_name' => 'R class'],
        ['brand_id' => 1, 'model_name' => 'SLC'],
        ['brand_id' => 1, 'model_name' => 'SLK class'],
        ['brand_id' => 1, 'model_name' => 'SLR Mclaren'],
        ['brand_id' => 1, 'model_name' => 'SL class'],
        ['brand_id' => 1, 'model_name' => 'Sprinter'],
        ['brand_id' => 1, 'model_name' => 'SR class'],
        ['brand_id' => 1, 'model_name' => 'T1'],
        ['brand_id' => 1, 'model_name' => 'Vaneo'],
        ['brand_id' => 1, 'model_name' => 'Viano'],
        ['brand_id' => 1, 'model_name' => 'Vito'],
        ['brand_id' => 1, 'model_name' => 'V class'],
        ['brand_id' => 1, 'model_name' => 'Khác'],
        # seeder mercedes model

        # seeder bmw model
        ['brand_id' => 2, 'model_name' => '3 Series'],
        ['brand_id' => 2, 'model_name' => '5 Series'],
        ['brand_id' => 2, 'model_name' => '7 Series'],
        ['brand_id' => 2, 'model_name' => 'X3'],
        ['brand_id' => 2, 'model_name' => 'X6'],
        ['brand_id' => 2, 'model_name' => 'X5'],
        ['brand_id' => 2, 'model_name' => '4 Series'],
        ['brand_id' => 2, 'model_name' => 'X7'],
        ['brand_id' => 2, 'model_name' => 'Z4'],
        ['brand_id' => 2, 'model_name' => '1 Series'],
        ['brand_id' => 2, 'model_name' => '2 Series'],
        ['brand_id' => 2, 'model_name' => '6 Series'],
        ['brand_id' => 2, 'model_name' => '8 Series'],
        ['brand_id' => 2, 'model_name' => 'Alpina'],
        ['brand_id' => 2, 'model_name' => 'i3'],
        ['brand_id' => 2, 'model_name' => 'i4'],
        ['brand_id' => 2, 'model_name' => 'i7'],
        ['brand_id' => 2, 'model_name' => 'i8'],
        ['brand_id' => 2, 'model_name' => 'iX'],
        ['brand_id' => 2, 'model_name' => 'iX3'],
        ['brand_id' => 2, 'model_name' => 'M1'],
        ['brand_id' => 2, 'model_name' => 'M2'],
        ['brand_id' => 2, 'model_name' => 'M3'],
        ['brand_id' => 2, 'model_name' => 'M4'],
        ['brand_id' => 2, 'model_name' => 'M5'],
        ['brand_id' => 2, 'model_name' => 'M6'],
        ['brand_id' => 2, 'model_name' => 'M8'],
        ['brand_id' => 2, 'model_name' => 'M Roadster'],
        ['brand_id' => 2, 'model_name' => 'X1'],
        ['brand_id' => 2, 'model_name' => 'X2'],
        ['brand_id' => 2, 'model_name' => 'X4'],
        ['brand_id' => 2, 'model_name' => 'XM'],
        ['brand_id' => 2, 'model_name' => 'Z1'],
        ['brand_id' => 2, 'model_name' => 'Z3'],
        ['brand_id' => 2, 'model_name' => 'Z8'],
        ['brand_id' => 2, 'model_name' => 'Khác'],
        # seeder bmw model

        # seeder audi model
        ['brand_id' => 3, 'model_name' => 'Q5'],
        ['brand_id' => 3, 'model_name' => 'Q7'],
        ['brand_id' => 3, 'model_name' => 'A6'],
        ['brand_id' => 3, 'model_name' => 'A4'],
        ['brand_id' => 3, 'model_name' => 'A8'],
        ['brand_id' => 3, 'model_name' => 'A5'],
        ['brand_id' => 3, 'model_name' => 'Q8'],
        ['brand_id' => 3, 'model_name' => 'Q2'],
        ['brand_id' => 3, 'model_name' => 'A7'],
        ['brand_id' => 3, 'model_name' => '100'],
        ['brand_id' => 3, 'model_name' => '200'],
        ['brand_id' => 3, 'model_name' => '80'],
        ['brand_id' => 3, 'model_name' => '90'],
        ['brand_id' => 3, 'model_name' => 'A1'],
        ['brand_id' => 3, 'model_name' => 'A2'],
        ['brand_id' => 3, 'model_name' => 'A3'],
        ['brand_id' => 3, 'model_name' => 'Allroad'],
        ['brand_id' => 3, 'model_name' => 'B4'],
        ['brand_id' => 3, 'model_name' => 'Cabriolet'],
        ['brand_id' => 3, 'model_name' => 'Coupe'],
        ['brand_id' => 3, 'model_name' => 'E-tron'],
        ['brand_id' => 3, 'model_name' => 'E-tron GT'],
        ['brand_id' => 3, 'model_name' => 'Q3'],
        ['brand_id' => 3, 'model_name' => 'Quattro'],
        ['brand_id' => 3, 'model_name' => 'R8'],
        ['brand_id' => 3, 'model_name' => 'RS2'],
        ['brand_id' => 3, 'model_name' => 'RS4'],
        ['brand_id' => 3, 'model_name' => 'RS6'],
        ['brand_id' => 3, 'model_name' => 'S2'],
        ['brand_id' => 3, 'model_name' => 'S3'],
        ['brand_id' => 3, 'model_name' => 'S4'],
        ['brand_id' => 3, 'model_name' => 'S5'],
        ['brand_id' => 3, 'model_name' => 'S6'],
        ['brand_id' => 3, 'model_name' => 'S8'],
        ['brand_id' => 3, 'model_name' => 'TT'],
        ['brand_id' => 3, 'model_name' => 'V8'],
        ['brand_id' => 3, 'model_name' => 'Khác'],
        # seeder audi model

        # seeder jeep model
        ['brand_id' => 4, 'model_name' => 'Wrangler'],
        ['brand_id' => 4, 'model_name' => 'Gladiator'],
        ['brand_id' => 4, 'model_name' => 'A2'],
        ['brand_id' => 4, 'model_name' => 'Cherokee'],
        ['brand_id' => 4, 'model_name' => 'Grand Cherokee'],
        ['brand_id' => 4, 'model_name' => 'Liberty'],
        ['brand_id' => 4, 'model_name' => 'CJ'],
        ['brand_id' => 4, 'model_name' => 'Compass'],
        ['brand_id' => 4, 'model_name' => 'Grand Wagoneer'],
        ['brand_id' => 4, 'model_name' => 'Renegade'],
        ['brand_id' => 4, 'model_name' => 'Khác'],
        # seeder jeep model

        # seeder mazda model
        ['brand_id' => 5, 'model_name' => '3'],
        ['brand_id' => 5, 'model_name' => 'CX5'],
        ['brand_id' => 5, 'model_name' => '6'],
        ['brand_id' => 5, 'model_name' => '2'],
        ['brand_id' => 5, 'model_name' => 'BT50'],
        ['brand_id' => 5, 'model_name' => 'CX8'],
        ['brand_id' => 5, 'model_name' => 'CX3'],
        ['brand_id' => 5, 'model_name' => 'CX 30'],
        ['brand_id' => 5, 'model_name' => '323'],
        ['brand_id' => 5, 'model_name' => '626'],
        ['brand_id' => 5, 'model_name' => '121'],
        ['brand_id' => 5, 'model_name' => '323F'],
        ['brand_id' => 5, 'model_name' => '5'],
        ['brand_id' => 5, 'model_name' => '929'],
        ['brand_id' => 5, 'model_name' => 'Atenza'],
        ['brand_id' => 5, 'model_name' => 'AZ'],
        ['brand_id' => 5, 'model_name' => 'Bongo Friendee'],
        ['brand_id' => 5, 'model_name' => 'Business'],
        ['brand_id' => 5, 'model_name' => 'B series'],
        ['brand_id' => 5, 'model_name' => 'Carol'],
        ['brand_id' => 5, 'model_name' => 'Clef'],
        ['brand_id' => 5, 'model_name' => 'Cronos'],
        ['brand_id' => 5, 'model_name' => 'CX7'],
        ['brand_id' => 5, 'model_name' => 'CX9'],
        ['brand_id' => 5, 'model_name' => 'Demino'],
        ['brand_id' => 5, 'model_name' => 'Eunos'],
        ['brand_id' => 5, 'model_name' => 'Familia'],
        ['brand_id' => 5, 'model_name' => 'Lantis'],
        ['brand_id' => 5, 'model_name' => 'Laputa'],
        ['brand_id' => 5, 'model_name' => 'Levante'],
        ['brand_id' => 5, 'model_name' => 'Millenia'],
        ['brand_id' => 5, 'model_name' => 'MPV'],
        ['brand_id' => 5, 'model_name' => 'MX 3'],
        ['brand_id' => 5, 'model_name' => 'MX 5'],
        ['brand_id' => 5, 'model_name' => 'MX 6'],
        ['brand_id' => 5, 'model_name' => 'Navajo'],
        ['brand_id' => 5, 'model_name' => 'Pickup'],
        ['brand_id' => 5, 'model_name' => 'Premacy'],
        ['brand_id' => 5, 'model_name' => 'Protege'],
        ['brand_id' => 5, 'model_name' => 'Rustler'],
        ['brand_id' => 5, 'model_name' => 'RX 7'],
        ['brand_id' => 5, 'model_name' => 'RX 8'],
        ['brand_id' => 5, 'model_name' => 'Scrum'],
        ['brand_id' => 5, 'model_name' => 'Sentia'],
        ['brand_id' => 5, 'model_name' => 'Spiano'],
        ['brand_id' => 5, 'model_name' => 'Tribute'],
        ['brand_id' => 5, 'model_name' => 'Vanstred'],
        ['brand_id' => 5, 'model_name' => 'Xedos 6'],
        ['brand_id' => 5, 'model_name' => 'Xedos 9'],
        ['brand_id' => 5, 'model_name' => 'Khác'],
        # seeder mazda model

        # ferarri model
        ['brand_id' => 6, 'model_name' => '488'],
        ['brand_id' => 6, 'model_name' => 'SF90 Stradale'],
        ['brand_id' => 6, 'model_name' => 'F12'],
        ['brand_id' => 6, 'model_name' => 'Roma'],
        ['brand_id' => 6, 'model_name' => 'F8'],
        ['brand_id' => 6, 'model_name' => 'California'],
        ['brand_id' => 6, 'model_name' => '360 Modena'],
        ['brand_id' => 6, 'model_name' => '456'],
        ['brand_id' => 6, 'model_name' => '458'],
        ['brand_id' => 6, 'model_name' => '550'],
        ['brand_id' => 6, 'model_name' => '575'],
        ['brand_id' => 6, 'model_name' => '612'],
        ['brand_id' => 6, 'model_name' => '812'],
        ['brand_id' => 6, 'model_name' => 'Barchetta'],
        ['brand_id' => 6, 'model_name' => 'Enze'],
        ['brand_id' => 6, 'model_name' => 'F 355'],
        ['brand_id' => 6, 'model_name' => 'F 360'],
        ['brand_id' => 6, 'model_name' => 'F 430'],
        ['brand_id' => 6, 'model_name' => 'F 50'],
        ['brand_id' => 6, 'model_name' => 'F 512'],
        ['brand_id' => 6, 'model_name' => 'GTC4Lusso'],
        ['brand_id' => 6, 'model_name' => 'Maranello'],
        ['brand_id' => 6, 'model_name' => 'Mondial'],
        ['brand_id' => 6, 'model_name' => 'Monza'],
        ['brand_id' => 6, 'model_name' => 'Portofino'],
        ['brand_id' => 6, 'model_name' => 'Testarossa'],
        ['brand_id' => 6, 'model_name' => 'Khác'],
        # ferarri model

        # mitsubishi model
        ['brand_id' => 7, 'model_name' => 'Xpander'],
        ['brand_id' => 7, 'model_name' => 'Triton'],
        ['brand_id' => 7, 'model_name' => 'Attrage'],
        ['brand_id' => 7, 'model_name' => 'Outlander'],
        ['brand_id' => 7, 'model_name' => 'Pajero Sport'],
        ['brand_id' => 7, 'model_name' => 'Pajero'],
        ['brand_id' => 7, 'model_name' => 'Jolie'],
        ['brand_id' => 7, 'model_name' => 'Mirage'],
        ['brand_id' => 7, 'model_name' => 'Grandis'],
        ['brand_id' => 7, 'model_name' => 'Lancer'],
        ['brand_id' => 7, 'model_name' => 'Zinger'],
        ['brand_id' => 7, 'model_name' => 'Outlander Sport'],
        ['brand_id' => 7, 'model_name' => '3000GT'],
        ['brand_id' => 7, 'model_name' => 'Airtek'],
        ['brand_id' => 7, 'model_name' => 'Canter'],
        ['brand_id' => 7, 'model_name' => 'Carisma'],
        ['brand_id' => 7, 'model_name' => 'Challenger'],
        ['brand_id' => 7, 'model_name' => 'Chariot'],
        ['brand_id' => 7, 'model_name' => 'Colt'],
        ['brand_id' => 7, 'model_name' => 'Debonair'],
        ['brand_id' => 7, 'model_name' => 'Delica'],
        ['brand_id' => 7, 'model_name' => 'Diamante'],
        ['brand_id' => 7, 'model_name' => 'Dion'],
        ['brand_id' => 7, 'model_name' => 'Eclipse'],
        ['brand_id' => 7, 'model_name' => 'EK wagon'],
        ['brand_id' => 7, 'model_name' => 'Emeraude'],
        ['brand_id' => 7, 'model_name' => 'Endeavor'],
        ['brand_id' => 7, 'model_name' => 'Evoliution'],
        ['brand_id' => 7, 'model_name' => 'FTO'],
        ['brand_id' => 7, 'model_name' => 'Galant'],
        ['brand_id' => 7, 'model_name' => 'Grunder'],
        ['brand_id' => 7, 'model_name' => 'GTO'],
        ['brand_id' => 7, 'model_name' => 'Hover'],
        ['brand_id' => 7, 'model_name' => 'IO'],
        ['brand_id' => 7, 'model_name' => 'Jeep'],
        ['brand_id' => 7, 'model_name' => 'L200'],
        ['brand_id' => 7, 'model_name' => 'L300'],
        ['brand_id' => 7, 'model_name' => 'L400'],
        ['brand_id' => 7, 'model_name' => 'Libero'],
        ['brand_id' => 7, 'model_name' => 'Minica'],
        ['brand_id' => 7, 'model_name' => 'Montero'],
        ['brand_id' => 7, 'model_name' => 'Pinin'],
        ['brand_id' => 7, 'model_name' => 'Proudia'],
        ['brand_id' => 7, 'model_name' => 'RVR'],
        ['brand_id' => 7, 'model_name' => 'Santamo'],
        ['brand_id' => 7, 'model_name' => 'Sapporo'],
        ['brand_id' => 7, 'model_name' => 'Savrin'],
        ['brand_id' => 7, 'model_name' => 'Sigma'],
        ['brand_id' => 7, 'model_name' => 'Space Gear'],
        ['brand_id' => 7, 'model_name' => 'Space Runner'],
        ['brand_id' => 7, 'model_name' => 'Space Star'],
        ['brand_id' => 7, 'model_name' => 'Space Wagon'],
        ['brand_id' => 7, 'model_name' => 'Starion'],
        ['brand_id' => 7, 'model_name' => 'Toppo'],
        ['brand_id' => 7, 'model_name' => 'Town Box'],
        ['brand_id' => 7, 'model_name' => 'Veryca'],
        ['brand_id' => 7, 'model_name' => 'Xforce'],
        ['brand_id' => 7, 'model_name' => 'Khác'],
        # mitsubishi model

        #nissan model
        ['brand_id' => 8, 'model_name' => 'Navara'],
        ['brand_id' => 8, 'model_name' => 'X-Trail'],
        ['brand_id' => 8, 'model_name' => 'Almera'],
        ['brand_id' => 8, 'model_name' => 'Sunny'],
        ['brand_id' => 8, 'model_name' => 'Teana'],
        ['brand_id' => 8, 'model_name' => 'Terra'],
        ['brand_id' => 8, 'model_name' => 'Kicks'],
        ['brand_id' => 8, 'model_name' => 'Grand Livina'],
        ['brand_id' => 8, 'model_name' => 'Bluebird'],
        ['brand_id' => 8, 'model_name' => 'Murano'],
        ['brand_id' => 8, 'model_name' => 'Maxima'],
        ['brand_id' => 8, 'model_name' => 'Qashqai'],
        ['brand_id' => 8, 'model_name' => '100NX'],
        ['brand_id' => 8, 'model_name' => '200SX'],
        ['brand_id' => 8, 'model_name' => '240SX'],
        ['brand_id' => 8, 'model_name' => '300ZX'],
        ['brand_id' => 8, 'model_name' => '350Z'],
        ['brand_id' => 8, 'model_name' => '370Z'],
        ['brand_id' => 8, 'model_name' => 'Altima'],
        ['brand_id' => 8, 'model_name' => 'Armada'],
        ['brand_id' => 8, 'model_name' => 'Avenir'],
        ['brand_id' => 8, 'model_name' => 'Bassara'],
        ['brand_id' => 8, 'model_name' => 'Cedric'],
        ['brand_id' => 8, 'model_name' => 'Cefiro'],
        ['brand_id' => 8, 'model_name' => 'Cima'],
        ['brand_id' => 8, 'model_name' => 'Crew'],
        ['brand_id' => 8, 'model_name' => 'Cube'],
        ['brand_id' => 8, 'model_name' => 'Elgrand'],
        ['brand_id' => 8, 'model_name' => 'Frontier'],
        ['brand_id' => 8, 'model_name' => 'Gloria'],
        ['brand_id' => 8, 'model_name' => 'GT-R'],
        ['brand_id' => 8, 'model_name' => 'Juke'],
        ['brand_id' => 8, 'model_name' => 'Langley'],
        ['brand_id' => 8, 'model_name' => 'Largo'],
        ['brand_id' => 8, 'model_name' => 'Laurel'],
        ['brand_id' => 8, 'model_name' => 'Leaf'],
        ['brand_id' => 8, 'model_name' => 'Liberty'],
        ['brand_id' => 8, 'model_name' => 'Livina'],
        ['brand_id' => 8, 'model_name' => 'Lucino'],
        ['brand_id' => 8, 'model_name' => 'Micra'],
        ['brand_id' => 8, 'model_name' => 'Moco'],
        ['brand_id' => 8, 'model_name' => 'NV'],
        ['brand_id' => 8, 'model_name' => 'Pathfinder'],
        ['brand_id' => 8, 'model_name' => 'Patrol'],
        ['brand_id' => 8, 'model_name' => 'Pick Up'],
        ['brand_id' => 8, 'model_name' => 'Pixo'],
        ['brand_id' => 8, 'model_name' => 'Prairie'],
        ['brand_id' => 8, 'model_name' => 'Presage'],
        ['brand_id' => 8, 'model_name' => 'Presea'],
        ['brand_id' => 8, 'model_name' => 'President'],
        ['brand_id' => 8, 'model_name' => 'Primastar'],
        ['brand_id' => 8, 'model_name' => 'Primera'],
        ['brand_id' => 8, 'model_name' => 'Pulsar'],
        ['brand_id' => 8, 'model_name' => 'Quest'],
        ['brand_id' => 8, 'model_name' => 'Rasheen'],
        ['brand_id' => 8, 'model_name' => 'Rogue'],
        ['brand_id' => 8, 'model_name' => 'R Nessa'],
        ['brand_id' => 8, 'model_name' => 'Safari'],
        ['brand_id' => 8, 'model_name' => 'Sentra'],
        ['brand_id' => 8, 'model_name' => 'Serena'],
        ['brand_id' => 8, 'model_name' => 'Silvia'],
        ['brand_id' => 8, 'model_name' => 'Skyline'],
        ['brand_id' => 8, 'model_name' => 'Stagea'],
        ['brand_id' => 8, 'model_name' => 'Stanza'],
        ['brand_id' => 8, 'model_name' => 'Terrano'],
        ['brand_id' => 8, 'model_name' => 'Tiida'],
        ['brand_id' => 8, 'model_name' => 'Tino'],
        ['brand_id' => 8, 'model_name' => 'Titan'],
        ['brand_id' => 8, 'model_name' => 'Urvan'],
        ['brand_id' => 8, 'model_name' => 'Vanette'],
        ['brand_id' => 8, 'model_name' => 'Versa'],
        ['brand_id' => 8, 'model_name' => 'Wingroad'],
        ['brand_id' => 8, 'model_name' => 'X Terra'],
        ['brand_id' => 8, 'model_name' => 'Khác'],
        #nissan model

        # suzuki model
        ['brand_id' => 9, 'model_name' => 'Swift'],
        ['brand_id' => 9, 'model_name' => 'XL7'],
        ['brand_id' => 9, 'model_name' => 'Super Carry Van'],
        ['brand_id' => 9, 'model_name' => 'Ertiga'],
        ['brand_id' => 9, 'model_name' => 'Super Carry Truck'],
        ['brand_id' => 9, 'model_name' => 'Carry'],
        ['brand_id' => 9, 'model_name' => 'Aerio'],
        ['brand_id' => 9, 'model_name' => 'Alto'],
        ['brand_id' => 9, 'model_name' => 'APV'],
        ['brand_id' => 9, 'model_name' => 'Baleno'],
        ['brand_id' => 9, 'model_name' => 'Cappuccino'],
        ['brand_id' => 9, 'model_name' => 'Celerio'],
        ['brand_id' => 9, 'model_name' => 'Ciaz'],
        ['brand_id' => 9, 'model_name' => 'Cultis Wagon'],
        ['brand_id' => 9, 'model_name' => 'Esteem'],
        ['brand_id' => 9, 'model_name' => 'Every Landy'],
        ['brand_id' => 9, 'model_name' => 'Grand Vitara'],
        ['brand_id' => 9, 'model_name' => 'Ignis'],
        ['brand_id' => 9, 'model_name' => 'Jimmy'],
        ['brand_id' => 9, 'model_name' => 'Kei'],
        ['brand_id' => 9, 'model_name' => 'Liana'],
        ['brand_id' => 9, 'model_name' => 'Samurai'],
        ['brand_id' => 9, 'model_name' => 'SJ'],
        ['brand_id' => 9, 'model_name' => 'SX4'],
        ['brand_id' => 9, 'model_name' => 'Twin'],
        ['brand_id' => 9, 'model_name' => 'Vitara'],
        ['brand_id' => 9, 'model_name' => 'Wagon R+'],
        ['brand_id' => 9, 'model_name' => 'X90'],
        ['brand_id' => 9, 'model_name' => 'Khác'],
        # suzuki model

        # tesla model
        ['brand_id' => 10, 'model_name' => '3'],
        ['brand_id' => 10, 'model_name' => 'S'],
        ['brand_id' => 10, 'model_name' => 'X'],
        ['brand_id' => 10, 'model_name' => 'Khác'],
        # tesla model

        # toyota model
        ['brand_id' => 11, 'model_name' => 'Vios'],
        ['brand_id' => 11, 'model_name' => 'Fortuner'],
        ['brand_id' => 11, 'model_name' => 'Innova'],
        ['brand_id' => 11, 'model_name' => 'Camry'],
        ['brand_id' => 11, 'model_name' => 'Corolla Altis'],
        ['brand_id' => 11, 'model_name' => 'Corolla Cross'],
        ['brand_id' => 11, 'model_name' => 'Land Cruiser'],
        ['brand_id' => 11, 'model_name' => 'Yaris'],
        ['brand_id' => 11, 'model_name' => 'Prado'],
        ['brand_id' => 11, 'model_name' => 'Veloz'],
        ['brand_id' => 11, 'model_name' => 'Wigo'],
        ['brand_id' => 11, 'model_name' => 'Hilux'],
        ['brand_id' => 11, 'model_name' => 'Raize'],
        ['brand_id' => 11, 'model_name' => 'Sienna'],
        ['brand_id' => 11, 'model_name' => '4 Runner'],
        ['brand_id' => 11, 'model_name' => '86'],
        ['brand_id' => 11, 'model_name' => 'Allion'],
        ['brand_id' => 11, 'model_name' => 'Alphard'],
        ['brand_id' => 11, 'model_name' => 'Altezza'],
        ['brand_id' => 11, 'model_name' => 'Aristo'],
        ['brand_id' => 11, 'model_name' => 'Aurion'],
        ['brand_id' => 11, 'model_name' => 'Avalon'],
        ['brand_id' => 11, 'model_name' => 'Avanza'],
        ['brand_id' => 11, 'model_name' => 'Avensis'],
        ['brand_id' => 11, 'model_name' => 'Aygo'],
        ['brand_id' => 11, 'model_name' => 'Blizzard'],
        ['brand_id' => 11, 'model_name' => 'Brevis'],
        ['brand_id' => 11, 'model_name' => 'C-HR'],
        ['brand_id' => 11, 'model_name' => 'Caldina'],
        ['brand_id' => 11, 'model_name' => 'Cami'],
        ['brand_id' => 11, 'model_name' => 'Carina'],
        ['brand_id' => 11, 'model_name' => 'Celica'],
        ['brand_id' => 11, 'model_name' => 'Century'],
        ['brand_id' => 11, 'model_name' => 'Chaser'],
        ['brand_id' => 11, 'model_name' => 'Corolla'],
        ['brand_id' => 11, 'model_name' => 'Corolla Verso'],
        ['brand_id' => 11, 'model_name' => 'Corona'],
        ['brand_id' => 11, 'model_name' => 'Corsa'],
        ['brand_id' => 11, 'model_name' => 'Cressida'],
        ['brand_id' => 11, 'model_name' => 'Cresta'],
        ['brand_id' => 11, 'model_name' => 'Crown'],
        ['brand_id' => 11, 'model_name' => 'Curren'],
        ['brand_id' => 11, 'model_name' => 'Cynos'],
        ['brand_id' => 11, 'model_name' => 'dB'],
        ['brand_id' => 11, 'model_name' => 'Duet'],
        ['brand_id' => 11, 'model_name' => 'Echo'],
        ['brand_id' => 11, 'model_name' => 'Estima'],
        ['brand_id' => 11, 'model_name' => 'Fj Cruiser'],
        ['brand_id' => 11, 'model_name' => 'Gaia'],
        ['brand_id' => 11, 'model_name' => 'Granvia'],
        ['brand_id' => 11, 'model_name' => 'Harrier'],
        ['brand_id' => 11, 'model_name' => 'Hiace'],
        ['brand_id' => 11, 'model_name' => 'Highlander'],
        ['brand_id' => 11, 'model_name' => 'Ipsum'],
        ['brand_id' => 11, 'model_name' => 'IQ'],
        ['brand_id' => 11, 'model_name' => 'KlugerV'],
        ['brand_id' => 11, 'model_name' => 'Liteace'],
        ['brand_id' => 11, 'model_name' => 'Mark II'],
        ['brand_id' => 11, 'model_name' => 'Matrix'],
        ['brand_id' => 11, 'model_name' => 'Mega Cruiser'],
        ['brand_id' => 11, 'model_name' => 'MR 2'],
        ['brand_id' => 11, 'model_name' => 'MR_S'],
        ['brand_id' => 11, 'model_name' => 'Nadia'],
        ['brand_id' => 11, 'model_name' => 'Opa'],
        ['brand_id' => 11, 'model_name' => 'Origin'],
        ['brand_id' => 11, 'model_name' => 'Paseo'],
        ['brand_id' => 11, 'model_name' => 'Picnic'],
        ['brand_id' => 11, 'model_name' => 'Platz'],
        ['brand_id' => 11, 'model_name' => 'Premio'],
        ['brand_id' => 11, 'model_name' => 'Previa'],
        ['brand_id' => 11, 'model_name' => 'Prius'],
        ['brand_id' => 11, 'model_name' => 'Progres'],
        ['brand_id' => 11, 'model_name' => 'Pronard'],
        ['brand_id' => 11, 'model_name' => 'Raum'],
        ['brand_id' => 11, 'model_name' => 'RAV4'],
        ['brand_id' => 11, 'model_name' => 'Rush'],
        ['brand_id' => 11, 'model_name' => 'Scepter'],
        ['brand_id' => 11, 'model_name' => 'Sequoia'],
        ['brand_id' => 11, 'model_name' => 'Sera'],
        ['brand_id' => 11, 'model_name' => 'Soarer'],
        ['brand_id' => 11, 'model_name' => 'Solara'],
        ['brand_id' => 11, 'model_name' => 'Starlet'],
        ['brand_id' => 11, 'model_name' => 'Supra'],
        ['brand_id' => 11, 'model_name' => 'Tacoma'],
        ['brand_id' => 11, 'model_name' => 'Tercel'],
        ['brand_id' => 11, 'model_name' => 'Townace'],
        ['brand_id' => 11, 'model_name' => 'Tundra'],
        ['brand_id' => 11, 'model_name' => 'Van'],
        ['brand_id' => 11, 'model_name' => 'Venza'],
        ['brand_id' => 11, 'model_name' => 'Verossa'],
        ['brand_id' => 11, 'model_name' => 'Verso'],
        ['brand_id' => 11, 'model_name' => 'Vista'],
        ['brand_id' => 11, 'model_name' => 'Windom'],
        ['brand_id' => 11, 'model_name' => 'Wish'],
        ['brand_id' => 11, 'model_name' => 'XA'],
        ['brand_id' => 11, 'model_name' => 'Yaris Cross'],
        ['brand_id' => 11, 'model_name' => 'Yaris Verso'],
        ['brand_id' => 11, 'model_name' => 'Zace'],
        ['brand_id' => 11, 'model_name' => 'Khác'],
        # toyota model

        # volkswagen model
        ['brand_id' => 12, 'model_name' => 'Teramont'],
        ['brand_id' => 12, 'model_name' => 'Tiguan'],
        ['brand_id' => 12, 'model_name' => 'Touareg'],
        ['brand_id' => 12, 'model_name' => 'Polo'],
        ['brand_id' => 12, 'model_name' => 'T-Cross'],
        ['brand_id' => 12, 'model_name' => 'Virtus'],
        ['brand_id' => 12, 'model_name' => 'Beetle'],
        ['brand_id' => 12, 'model_name' => 'Bora'],
        ['brand_id' => 12, 'model_name' => 'Caddy'],
        ['brand_id' => 12, 'model_name' => 'California'],
        ['brand_id' => 12, 'model_name' => 'Corrado'],
        ['brand_id' => 12, 'model_name' => 'Crafter'],
        ['brand_id' => 12, 'model_name' => 'D1'],
        ['brand_id' => 12, 'model_name' => 'Derby'],
        ['brand_id' => 12, 'model_name' => 'Eos'],
        ['brand_id' => 12, 'model_name' => 'Golf'],
        ['brand_id' => 12, 'model_name' => 'Golf Plus'],
        ['brand_id' => 12, 'model_name' => 'Iltea'],
        ['brand_id' => 12, 'model_name' => 'Jetta'],
        ['brand_id' => 12, 'model_name' => 'Kaefer'],
        ['brand_id' => 12, 'model_name' => 'Lupo'],
        ['brand_id' => 12, 'model_name' => 'Multivan'],
        ['brand_id' => 12, 'model_name' => 'New Beetle'],
        ['brand_id' => 12, 'model_name' => 'Passat'],
        ['brand_id' => 12, 'model_name' => 'Phaeton'],
        ['brand_id' => 12, 'model_name' => 'Routan'],
        ['brand_id' => 12, 'model_name' => 'Santana'],
        ['brand_id' => 12, 'model_name' => 'Scirocco'],
        ['brand_id' => 12, 'model_name' => 'Sharan'],
        ['brand_id' => 12, 'model_name' => 'Solo'],
        ['brand_id' => 12, 'model_name' => 'Taro'],
        ['brand_id' => 12, 'model_name' => 'Touran'],
        ['brand_id' => 12, 'model_name' => 'Transporter'],
        ['brand_id' => 12, 'model_name' => 'Vento'],
        ['brand_id' => 12, 'model_name' => 'Viloran'],
        ['brand_id' => 12, 'model_name' => 'Khác'],
        # volkswagen model
    ]);
  }
}
